### ISSUE TITLE
Wrong WML variable names in translation (ANL, UtBS and core)

### ISSUE THREAD

**Issue by stevecotton** [hrubymar10/wesnoth-cs#170]
Thanks for having a bug-tracker for your translation, it's so nice to know where to log issues.

These were discovered in wesnoth/wesnoth#4436:
```
E: po/wesnoth-anl/cs.po: msgid "<span color='green'>Mining</span>\nMiners produce +1 gold\nStudy Progress: $player_$side_number|.mining.progress|/$player_$side_number|.mining.target": uses 'farming.progress' and 'farming.target' in msgstr
E: po/wesnoth-anl/cs.po: msgid '$player_$side_number|.name|’s mines now produce $player_$side_number|.mining.gold gold.': 'farming.gold' in msgstr

E: po/wesnoth/cs.po: msgid 'Connecting to $server_address|...': '$server_adress' in msgstr but '$server_address' in msgid

E: po/wesnoth-utbs/cs.po: msgid 'At the start of each turn, any unit currently in this pool will heal 10 hitpoints and will not be affected by the heat in the cavern. Of course, if the unit leaves this pool, it will suffer the standard $heat_damage damage each turn from the heat.': '$temp_damage' in msgstr but '$heat_damage' in msgid
```

Some more where I'm not sure if they're an issue or not. I can't read Czech, but assume they can be correct without the units' names:
```
E: po/wesnoth-anl/cs.po: msgid '$player_$side_number|.name|, we have finished researching warfare. Right-click on a mage in a university to select a unit to recruit.': '$player_$side_number|.name' not in msgstr
E: po/wesnoth-dw/cs.po: msgid 'Thank you, $spy_unit.name|. I will keep that in mind, but it may be hard for us to stop him with that teleporting trick he has.': '$spy_unit.name' not in msgstr
E: po/wesnoth-httt/cs.po: msgid 'As $unit.name| places her hand around the glittering leather hilt, the sword roars to life! Strangely, she feels no heat once she picks it up, yet the grass at her feet bursts into flame as she tests the heft of this mighty weapon.': '$unit.name' not in msgstr
E: po/wesnoth-low/cs.po: msgid 'Let us pursue the orc who murdered $unit.name|!': '$unit.name' not in msgstr
E: po/wesnoth-low/cs.po: msgid 'Evil takes many forms, my love. Today we see another of its faces... and must defeat it again. Prepare to die, $betrayer|!': '$betrayer' not in msgstr
E: po/wesnoth-low/cs.po: msgid 'Hold, $unit.name|! Now we fight for Landar!': '$unit.name' not in msgstr
E: po/wesnoth-low/cs.po: msgid 'Hold your hand, $unit.name|! $second_unit.name| is on our side!': '$unit.name' not in msgstr
E: po/wesnoth-low/cs.po: msgid 'Forgive me $unit.name|. I will sing your name in praise under the stars!': '$unit.name' not in msgstr
E: po/wesnoth-low/cs.po: msgid 'We must all pass, $second_unit.name|. Make your song beautiful...': '$second_unit.name' not in msgstr
E: po/wesnoth-low/cs.po: msgid 'Forgive me, $unit.name|, this victory brings me no joy.': '$unit.name' not in msgstr
E: po/wesnoth-low/cs.po: msgid 'Farewell $unit.name. Your loyal service won’t be forgotten.': '$unit.name' not in msgstr
E: po/wesnoth-sotbe/cs.po: msgid 'Bye bye, $unit.name|!': '$unit.name' not in msgstr
E: po/wesnoth-utbs/cs.po: msgid '$unit.name|, be quiet, I’ll explain it all later.': '$unit.name' not in msgstr
```

**Comment by celerini** [comment]
Thanks for reporting bugs in our translations. Those [should be fixed](https://github.com/hrubymar10/wesnoth-cs/commit/a77847d0e9cf8da43c91075b416181c18f8cfac4) for now and are planned to be sent to @ivanovic on 2021-09-10.

As for missing unit.name - [fixed one in narration](https://github.com/hrubymar10/wesnoth-cs/commit/845138c5d81cdd30ec027fd901d8a09409c6a71c), but others are a grammatical case cases where unit.name is missing on purpose. Some can be fixed by unnatural circumlocution (to force use of the first grammatical case, which is unit.name), but most of them are [vocatives](https://en.wikipedia.org/wiki/Vocative_case#Czech) for whose we need correct suffixes. In Czech we have only for noun's inflection (declension) three genders times four paradigms times seven cases - each can have a different suffix.

I enjoyed a good time with creating generic Czech location names (both [geographical](https://github.com/hrubymar10/wesnoth-cs/commit/9cdd33ec1ed6c0e75abaa0af93c18ee3be4ff26c) and [villages](https://github.com/hrubymar10/wesnoth-cs/commit/69dc7d4e18481d3ac6b85d6fa56bec388c9f18f5)), but although I assume, that the Context-Free Generator can be used for unit.name as well, I suspect it is not worth my time for now.

**Comment by stevecotton** [comment]
> `E: po/wesnoth-anl/cs.po: msgid "<span color='green'>Mining</span>\nMiners produce +1 gold\nStudy Progress: $player_$side_number|.mining.progress|/$player_$side_number|.mining.target": uses 'farming.progress' and 'farming.target' in msgstr`

That one's become truncated in commit 367c87c37d2f5f07c53e516fa543bc8138b4fdb4 (in the main repo). The new translation ends before the `mining.target`.

**Comment by celerini** [comment]
mea culpa

It' s hopefuly fixed now. The update was sent to Nils.

**Comment by celerini** [comment]
Are there still any issues, or can we close this?

**Comment by stevecotton** [comment]
All looks good now, thanks.
